name: StyleAI
options:
  bundleIdPrefix: com.styleai
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.2"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: true
    ENABLE_USER_SCRIPT_SANDBOXING: true

targets:
  StyleAI:
    type: application
    platform: iOS
    sources:
      - path: StyleAI
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.styleai.app
        PRODUCT_NAME: "Style AI"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Style AI necesita acceso a tus fotos para el Probador Virtual."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Style AI necesita permiso para guardar los looks generados."
        INFOPLIST_KEY_NSCameraUsageDescription: "Style AI necesita la cámara para escanear prendas."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Style AI usa tu ubicación para obtener el clima y recomendarte outfits."
        INFOPLIST_KEY_CFBundleDisplayName: "Style AI"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: false
        CODE_SIGNING_ALLOWED: false
        CODE_SIGN_ENTITLEMENTS: ""
        DEVELOPMENT_TEAM: ""
